### ISSUE TITLE
datacenter-deploy-secure doesn't work

### ISSUE THREAD

**Issue by mircea-cm** [hashicorp/learn-consul-docker#2]
Hello,
following the tutorial from https://learn.hashicorp.com/tutorials/consul/docker-compose-datacenter, I keep receiving the error **No private IPv4 address found** when running the docker-compose.yml file

**Comment by eddie-rowe** [comment]
Thank you for the feedback @mircea-cm and apologies for the delay.
The certificate in datacenter-deploy-secure has been updated with a 3 year certificate.
